name: Python Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.4'
      - name: Install dependencies
        run: |
          pip3 install pipenv
          ./go.sh setup
      - name: Test with pytest
        run: |
          ./go.sh tests